#ifndef CONSTANTS_HEADER
#define CONSTANTS_HEADER

#include <stdlib.h>
#include <stdint.h>


// VARIABLES
#define BUFFER_SIZE 64
#define I2C_ADDR 8

#define PULSE_DELAY_HOMING_XY 400
#define PULSE_DELAY_HOMING_Z 100
#define PUSLE_DELAY_PAINT_HOR 400
#define PUSLE_DELAY_PAINT_VERT 120
#define PUSLE_DELAY_PAINT_VERT_DISPENSE 300

#define CXY_SIZE_X 20000
#define CXY_SIZE_Y 19000
#define CXY_SIZE_Z 20000

#define Z_TEMP_HOME_POSITION 11200

#define TOOL_INDEX_NONE 8
#define TOOL_INDEX_PAINT_MIXER 0
#define TOOL_INDEX_CUP_EXTRACTOR 1

#define PAINT_STEPS_PER_UNIT 240

#define HOME_OFFSET_X_Y 125
#define HOME_OFFSET_Z 600

#define PAINT_VERT_CLEAR_POSITION 0

#define ERROR_RESPONSE 0
#define SUCCESS_RESPONSE 1

#define HOME_CODE 0
#define MOVE_CODE 1
#define EXCHANGE_TOOL_CODE 2
#define CUP_POSITION_CODE 3
#define DISPENSE_PAINT_CODE 4
#define CONFIGURE_CODE 5
#define MEASURE_CODE 6
#define MOVE_ARC_CODE 7
#define WASH_TOOL_CODE 8

#define MOTOR_ELECTROMAGNET 0
#define MOTOR_CUP_HOLDER 1
#define MOTOR_OTHER 2
#define MOTOR_CUP_DISPENSER 3

#define CUP_HOLDER_POSITION_HIDDEN 0
#define CUP_HOLDER_POSITION_STANDARD 1
#define CUP_HOLDER_POSITION_EXTENDED 2

#define COLOR_BUFFER_SIZE 20
#define CONFIGURE_BUFFER_SIZE 24

// Positions
#define POSITION_Y_CLEARANCE 1500

#define POSITION_X_SUBSPACE_ZERO 0
#define POSITION_Y_SUBSPACE_ZERO 3000

#define POSITION_CUP_DISPENSER_X 11380
#define POSITION_CUP_DISPENSER_Y 1250

#define POSITION_TOOL_CHANGER_Z_RELEASE 2230
#define POSITION_TOOL_CHANGER_Z_GRIP 9900
#define POSITION_TOOL_CHANGER_Y_CLOSE 1200
#define POSITION_TOOL_CHANGER_Y_HOVER 0

#define POSITION_PAINT_MIXER_INSERTED_Z 8744
#define POSITION_PAINT_MIXER_POWER_X 18915
#define POSITION_PAINT_MIXER_POWER_Y 150

#define POSITION_PAINT_DISPENSER_X 20000
#define POSITION_PAINT_DISPENSER_Y 1250

#define POSITION_WASHING_STATION_X 16890
#define POSITION_WASHING_STATION_Y 390
#define POSITION_WASHING_STATION_INSERT_Z 12500
#define POSITION_WASHING_STATION_HOVER_Z 5000
#define POSITION_WASHING_STATION_WIPE_Z 1800
#define POSITION_WASHING_STATION_WIPE_X 15200

#define POSITION_CUP_EJECTOR_Z_RECIEVE 15780
#define POSITION_CUP_EJECTOR_Z_EJECT 5600
#define POSITION_CUP_EJECTOR_X_BEFORE 13990
#define POSITION_CUP_EJECTOR_X_AFTER 14650
#define POSITION_CUP_EJECTOR_Y 0

// PINS
#define PIN_SDA 0
#define PIN_SCL 1
#define PIN_A_DIR 2
#define PIN_A_STP 3
#define PIN_B_DIR 4
#define PIN_B_STP 5
#define PIN_AB_EN 6
#define PIN_Z_DIR 7
#define PIN_Z_STP 8
#define PIN_Z_EN 9
#define PIN_X_LIM 10
#define PIN_Y_LIM 11
#define PIN_Z_LIM 12
#define PIN_REFLECTANCE 13
#define PIN_BUSY_LINE 14
#define PIN_MOSFET_EN 15

#define PIN_PAINT_LIM 16
#define PIN_PAINT_VERTICAL_STP 17
#define PIN_PAINT_DIR 18
#define PIN_PAINT_HORIZONTAL_STP 19
#define PIN_PAINT_EN 20
#define PIN_IN8 21
#define PIN_IN6_IN7 22
#define PIN_IN4_IN5 26
#define PIN_IN2_IN3 27
#define PIN_IN1 28

#endif
